### ISSUE TITLE
Remove "closing at" from sidebar items

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#11]
![screen shot 2014-09-10 at 12 42 27 pm](https://cloud.githubusercontent.com/assets/2538465/4220531/a216bcc4-3901-11e4-8650-ea1d4f68ef12.png)

These are not needed when treating a single document and each list item is a section of it.

What do you say @piamancini, @slifszyc, @vmariano  ?

**Comment by piamancini** [comment]
agreed. It's redundant and confusing.

P.
piamancini.com
t: @piamancini
s: piamancini
democracyos.org
democraciaenred.org

**Comment by sachalifs** [comment]
Your signature on your comment is also redundant and confusing.

Just kidding :dancers: 

I agree on this one, too.

**Comment by gvilarino** [comment]
Then it's no longer a question but an issue :shipit:
