### ISSUE TITLE
[law] Change Twitter text

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/demos#110]
Should be: 

> Estamos debatiendo "`#{law.title}`", en demos.legislatura.gov.ar. Participá vos también #YoVoto @`#{law.twitterHandle}`

**Comment by jfresco** [comment]
The Twitter Intent API seems to behave oddly.
With this link address `http://twitter.com/share?text=Estamos%20debatiendo%20%22Aumentar%20la%20inversi%C3%B3n%20en%20Educaci%C3%B3n%22%2C%20en%20demos.legislatura.gov.ar.%20Particip%C3%A1%20vos%20tambi%C3%A9n%20%23YoVoto%20%40Maxiferraro` is generating this:
![image](https://cloud.githubusercontent.com/assets/4335188/5149480/2579ff52-71a8-11e4-9174-675c83d6cecd.png)

It's putting the referrer URL (not shortened) in the tweet, stealing characters.
I see two possible solutions:
- Set always the URL to http://demos.legislatura.gov.ar. The tweet will look like this:
  ![image](https://cloud.githubusercontent.com/assets/4335188/5149539/92b03b9a-71a8-11e4-89bc-20d9c6d0b39b.png)
- Make a shortened URL for each law and put it in the tweet, like this:
  ![image](https://cloud.githubusercontent.com/assets/4335188/5149573/d890e786-71a8-11e4-9863-ff71ace02b29.png)

(still seems to be insufficient).

What do you think?

**Comment by afrizzera** [comment]
18 characters left. It´s more than ok!
