### ISSUE TITLE
Add Min-Height 

### ISSUE THREAD

**Issue by piamancini** [DemocraciaEnRed/demos#112]
Please add min-height to bill divs in landing so they have same bottom line. 
![screen shot 2014-11-23 at 12 54 48 pm](https://cloud.githubusercontent.com/assets/3671070/5158083/f7ab57c4-730f-11e4-9fb5-dfa13f808ae1.png)

**Comment by jfresco** [comment]
Now looks perfectly aligned:
![selection_027](https://cloud.githubusercontent.com/assets/4335188/5189899/4b979ff8-74c0-11e4-9c7c-17c0514380a3.png)

**Comment by piamancini** [comment]
genios.

P.
piamancini.com
t: @piamancini
s: piamancini
democracyos.org
democraciaenred.org
