### ISSUE TITLE
Remove mandatory "link to source"

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#12]
![screen shot 2014-09-10 at 12 55 45 pm](https://cloud.githubusercontent.com/assets/2538465/4220685/fddda71a-3902-11e4-86d9-5b675bccd8f9.png)

As per [this issue](https://github.com/DemocracyOS/app/issues/425)

**Comment by sachalifs** [comment]
Closed in [DemocracyOS/app Issue 425](https://github.com/DemocracyOS/app/issues/425)
