### ISSUE TITLE
Make "Read more..." clause-truncation text customizable

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#13]
![screen shot 2014-09-10 at 12 59 07 pm](https://cloud.githubusercontent.com/assets/2538465/4220838/3191b4a6-3904-11e4-9866-41d1f28abf07.png)

As per [this issue](https://github.com/DemocracyOS/app/issues/426)

**Comment by gvilarino** [comment]
Sorry of the labeling confusion

**Comment by sachalifs** [comment]
Solved in [DemocracyOS/app Issue 426](https://github.com/DemocracyOS/app/issues/426)
