### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#15]
Use correct one, with white background.

**Comment by gvilarino** [comment]
Can we get a reference on this, @piamancini @mairwilliams ?

**Comment by piamancini** [comment]
are we talking about the Legislatura logo? sorry, request is unclear.

**Comment by vmariano** [comment]
Yes, The app logo.
![logo](https://cloud.githubusercontent.com/assets/796960/4222723/1430e410-3916-11e4-9da4-bac051175dbc.png)

**Comment by gvilarino** [comment]
@piamancini Legislatura logo. This is the `/demos` repo

**Comment by mairwilliams** [comment]
this is the logo with white background

![legis-whitebackground](https://cloud.githubusercontent.com/assets/7072387/4223624/a2ebb66a-391d-11e4-93fa-7a13ca49149c.jpeg)

and this is transparent, but it has words too. I can cut it if you prefer

![legis-transparente](https://cloud.githubusercontent.com/assets/7072387/4223645/dc1574d0-391d-11e4-934b-3fbb238c77cd.png)

**Comment by gvilarino** [comment]
Thanks @mairwilliams, we'll do ok with this.
