### ISSUE TITLE
Viral enhancements

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#17]
It's been suggested by @ebrenman that we add a viral factor by offering users a chance to share their interaction on social networks. The scope of this isn't clear.

What interactions should we contemplate?

Should this happen on every and all interactions? It could get really annoying as a user.

Should this wait until we have social sign-in and leverage that?

**Comment by sachalifs** [comment]
![screen shot 2014-09-11 at 3 54 46 pm](https://cloud.githubusercontent.com/assets/1213542/4239894/2b674c30-39e5-11e4-83c3-efba110aad34.png)
![screen shot 2014-09-11 at 3 55 00 pm](https://cloud.githubusercontent.com/assets/1213542/4239895/2b91ef94-39e5-11e4-9290-3ee957ef8cf9.png)
Could these be a possibility?

**Comment by sachalifs** [comment]
Those are desktop and mobile screenshots respectively

**Comment by ebrenman** [comment]
We should contemplate two types of actions:
- Commenting or replying another user's comment
- Voting

The message should be sometthing like:

Facebook

FirstName LastName  Ha votado una ley
September 9 at 7:28pm · via DemocracyOS

Boleto Estudiantil en la Ciudad

Este proyecto busca otorgar una reducción en la tarifa del subte durante el ciclo lectivo para los estudiantes y docentes con residencia en la Ciudad de Buenos Aires, beneficio al que se conoce como "Boleto Estudiantil". 

In the case of a comment, the text should be the user's comment (or an exctract of if)

e

---

Mi charla en TEDxRioDeLaPlata | El último de los Brenman 

>  https://www.youtube.com/watch?v=d5GqiVrZk1Y

**Comment by gvilarino** [comment]
@ebrenman I guess what you're talking about then is got more to do with the concept of [custom stories](https://developers.facebook.com/docs/opengraph/overview) based on the facebook Open Graph.

For this to happen, I'm afraid we'll need to have facebook auth; it can't happen by itself. More reference [here](https://developers.facebook.com/docs/opengraph).

The 'forced popup' approach wouldn't make facebook login a pre-requirement but would instead rely on existing FB sessions on the user's browser. Still, I find this to be very intrusive and anoying.

And I'm not clear about what the approach would then be wiht Twitter or Google+

**Comment by ebrenman** [comment]
Yes, the custom stories is the right approach. 
e

---

Mi charla en TEDxRioDeLaPlata | El último de los Brenman 

>  https://www.youtube.com/watch?v=d5GqiVrZk1Y
