### ISSUE TITLE
Basic bill proposal layout

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#21]
The basic proposal layout is as follows

![screen shot 2014-10-16 at 3 27 44 pm](https://cloud.githubusercontent.com/assets/2538465/4668050/2aff03e4-5562-11e4-964a-6a5d3ea3e608.png)

It includes:
- Bill media title
- Bill author (with picture, name and political membership)
- Picture for the bill
- Bill summary
- Link to source
- Ranking module

Just implement this based on hte wireframe. Other features/details will be specified elsewhere.

**Comment by sachalifs** [comment]
Bill author should link users to their twitter account.

**Comment by gvilarino** [comment]
@slifszyc yea, but let's leave that for another issue; this concerns only basic layout. We actually need @pazarando to provide updated styles for this. Maybe with some help from @mjlescano

**Comment by pazarando** [comment]
This is the final design (I just send this to the rest of the team so we should wait for some feedback about this)
- The text "(saber más)" should display a two lines explanation text. Moving a little bit down the bill layout. Preview atached.
- The little line bellow the "saber más" texts is a progress bar. I imagined it like this: 
  http://kalasoo.github.io/NumberProgressBar/
- The main bill body mesures 1012 px so it will fit without adjustments in the 1024 monitors resolutions. After that breakpoint we need to re-order the elements. Im attaching a .jpg with the mobile design. 

We will be working with @mjlescano this weekend so you can work in it as soon as possible!

![basic bill proposal layout-01](https://cloud.githubusercontent.com/assets/4235126/4678027/1620d8c4-55f0-11e4-84b5-b576b4926912.jpg)

![saber mas-detail-08](https://cloud.githubusercontent.com/assets/4235126/4678128/73c99a3c-55f1-11e4-83f0-1b5876d71b72.jpg)

![mobile-design-09](https://cloud.githubusercontent.com/assets/4235126/4678218/f5e1dc9a-55f2-11e4-82a2-2be44c53ff3d.jpg)

**Comment by mjlescano** [comment]
Added the upper part of the bill proposal layout on branch **bill-proposal-demo**

I created 2 routes just for demoing/testing:
- /bill-proposal-demo/show : Single view for a bill
- /bill-proposal-demo : Example to be used on the list of bills

Didn't follow the component style on purpose, I'm just getting used to it :P.
Also, @gvilarino and @slifszyc please correct me if I don't follow any convention rewarding JS, Jade or Styl.

**Comment by sachalifs** [comment]
@mjlescano [here](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTING.md#coding-style) we have our coding styles and conventions for you to check if you want, but yours in f2afe15ea2113708980ca54206b42c960763ea42 were totally fine, thank you very much!

We should add navigation (with the bottom arrows) and voting options ('how much interested are you on this project?'), as well as responsive capabilities. Do you think you could do that or do you prefer me to do it? Have you already started?

**Comment by mjlescano** [comment]
1. Great :)
2. Yes, i'm on it.

Also,

Are we currently using any custom font? Saw the lib/flaticons, but, there's a way to add another svg to it? If not I could add one.

Also, do you know any mixins library for stylus that is component compatible? I know [Kouto](https://github.com/krkn/kouto-swiss) and [nib](https://github.com/tj/nib) but neither is componetized.

**Comment by gvilarino** [comment]
@mjlescano it shouldn't be too different than [adding custom tag images](https://github.com/DemocracyOS/app/wiki/How-to-add-new-tag-images).

**Comment by pazarando** [comment]
A few design adjustments we start discussing by email:
- We should add a text description to the forward and next bottoms. In case its not clear for everybody.
- The progress bar will include a number reference like "1/20"

![demos-pantallas-02](https://cloud.githubusercontent.com/assets/4235126/4716988/031f0eae-590f-11e4-97db-33e7828d0f1a.jpg)

-------- Shares

I think its useful to have shares in each bill proposal, because we know there's going to be users specially interested in some of them. Its important this actions wont take you out of the platform.

I'm worried about how to include them, without loosing users focus on voting.
So I made 3 options we can discuss.

![demos-pantallas-09](https://cloud.githubusercontent.com/assets/4235126/4717029/6f75ab94-590f-11e4-9912-329bd3988a11.jpg)

![demos-pantallas-10](https://cloud.githubusercontent.com/assets/4235126/4717034/7c2f9b10-590f-11e4-811f-03032f1d3b8a.jpg)

![demos-pantallas-11](https://cloud.githubusercontent.com/assets/4235126/4717035/7c31d682-590f-11e4-962a-60d5fdf2acce.jpg)

**Comment by sachalifs** [comment]
@mjlescano both [kuoto](https://github.com/krkn/kouto-swiss) and [nib](https://github.com/tj/nib) are server side components, as the `app.css` file is generated and served by the server.

I'm digging into it to include it, it's a cool feature.

**Comment by sachalifs** [comment]
@mjlescano I have included [kuoto](http://kouto-swiss.io/) on [this branch](https://github.com/DemocraciaEnRed/demos/tree/add/kouto-swiss) for you to be able to use it.

Remember to `make clean && make` for npm to install it.

**Comment by gvilarino** [comment]
@mjlescano As long as we keep support for existing code, every upgrade is welcome

**Comment by mjlescano** [comment]
thanks @slifszyc!

**Comment by mjlescano** [comment]
The final version of the bill layout, with responsiveness it's here: /bill-proposal-demo/show
