### ISSUE TITLE
Bill ranking

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#24]
Users should be able to 'rank' bills based on how important it would be for them for each one to be discussed during phase 2.

The wireframe is like this:
![screen shot 2014-10-16 at 11 23 41 am](https://cloud.githubusercontent.com/assets/2538465/4669412/1766c0cc-556e-11e4-8384-8b3ca7e1ed5d.png)

From left to right, growing levels of importance.

Vote weight/value is TBD. For the time being just store a `name` or `id` associated to the option. This would help with handling the `skip` option, as well as leaving different vote weighting approaches open for discussion/test.

As for the wireframe, I don't like how the meter isn't centered and how the skip looks. We need more input from @pazarando here.

**Comment by pazarando** [comment]
As is set in the design this should look like this. 

![screen shot 2014-10-17 at 10 44 13](https://cloud.githubusercontent.com/assets/4235126/4679651/b6552562-5603-11e4-958e-fa9cdf28a3bc.png)

And like this in mobile devises: 

![screen shot 2014-10-17 at 10 46 19](https://cloud.githubusercontent.com/assets/4235126/4679688/040dd8d0-5604-11e4-9e8d-336f94d302d6.png)

Please take into account that this designs are not approved by the rest of the team yet.
