### ISSUE TITLE
All bills summary

### ISSUE THREAD

**Issue by pazarando** [DemocraciaEnRed/demos#25]
This is the last screen were you can find all your votes, go back to change them and see next dates.

I would like to discuss how to include the share buttons here, there are two design options:

![demos-pantallas-12](https://cloud.githubusercontent.com/assets/4235126/4717435/f21a2354-5914-11e4-99e8-596bd4a5bc55.jpg)
![demos-pantallas-13](https://cloud.githubusercontent.com/assets/4235126/4717436/f225626e-5914-11e4-91f1-151a1088d0a3.jpg)

**Comment by gvilarino** [comment]
I believe the second one makes more sense.

Still, the `law` summary pile up is probably a nice-to-have because of time restrictions.

**Comment by mairwilliams** [comment]
I like the second one, the first one looks nice too but the "share" section
is in the same visual field of the projects already voted, and if the user
doesn't want to edit he may just overlook the whole thing. In the second
case it's visually part of the "gracias por sumar tu opinión" message.

**Comment by sachalifs** [comment]
Check box heights with the laws on [test-demos](http://test-demos.herokuapp.com)

**Comment by gvilarino** [comment]
Pictures are broken and we're still missing the voting options

![screen shot 2014-11-03 at 5 59 30 pm](https://cloud.githubusercontent.com/assets/2538465/4890161/7ae2c100-639c-11e4-9a3a-d8e2b181bdaf.png)
