### ISSUE TITLE
Add projects page

### ISSUE THREAD

**Issue by sachalifs** [DemocraciaEnRed/demos#27]
![screen shot 2014-10-21 at 2 34 06 pm](https://cloud.githubusercontent.com/assets/1213542/4723538/868b94cc-5948-11e4-9c6e-8e26bcf01475.png)
This page should explain how projects were selected for this instance and display a list of the projects are available, linking to each one's voting page

**Comment by pazarando** [comment]
I thought the name of the laws in the second question could be links to the bill layout of that law.

Here is the .png of the icon
![demos-question-icon-15](https://cloud.githubusercontent.com/assets/4235126/4723651/9b53ac68-5949-11e4-94ad-92f6703b88be.png)

I you preferre I can email you the .svg

**Comment by sachalifs** [comment]
Please, email it to me if you can. Just the question marks. With no background, I mean.

**Comment by sachalifs** [comment]
And yes, to answer your question, that's what I intended to say with 'each one's voting page'
