### ISSUE TITLE
Bill sharing

### ISSUE THREAD

**Issue by mjlescano** [DemocraciaEnRed/demos#28]
We have 3 options to discuss:

![7c31d682-590f-11e4-962a-60d5fdf2acce](https://cloud.githubusercontent.com/assets/558901/4729763/4fdb842e-598d-11e4-97d8-8abb6c049702.jpg)
![6f75ab94-590f-11e4-9912-329bd3988a11](https://cloud.githubusercontent.com/assets/558901/4729762/4fd85236-598d-11e4-8a29-10224fe9b664.jpg)
![7c2f9b10-590f-11e4-811f-03032f1d3b8a](https://cloud.githubusercontent.com/assets/558901/4729764/4fdc79ba-598d-11e4-88de-2253d2940d89.jpg)

When the users click on a share button, it should open a popup/modal window with the share options, so the user is not taken out. This gist shows how to do it: https://gist.github.com/mjlescano/448266c65de550cbe291

**Comment by mairwilliams** [comment]
I like the first one visually and the third one because of the "call to action". As a user I would pick the first one.

—

**Comment by gvilarino** [comment]
I believe this discussion should be merged with #17
