### ISSUE TITLE
Title area

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#30]
The text that goes above all bills, over the background

**Comment by sachalifs** [comment]
which font is used for the title?

**Comment by sachalifs** [comment]
@gvilarino are we adding the "Saber más" area as well? Where does it go? `/about` or `/projects`?

**Comment by gvilarino** [comment]
I believe those should be `/acerca-de` and `/proyectos` for this instance.

**Comment by pazarando** [comment]
I didn´t have the font used in dos when i did the design so i used another.
I think its better to keep using the freight-sans-pro in this case too.

**Comment by sachalifs** [comment]
sorry, I meant this logo 
![screen shot 2014-10-29 at 10 23 32 am](https://cloud.githubusercontent.com/assets/1213542/4826286/d1b36a34-5f6e-11e4-9334-2236a0300036.png)

do you have that logo? can you email it please?

**Comment by sachalifs** [comment]
or upload it here, as well

**Comment by pazarando** [comment]
Just in case to keep the orden:

![demos-logo-header](https://cloud.githubusercontent.com/assets/4235126/4827002/87f88058-5f75-11e4-9e77-a32a768f68a2.png)
![demos-logo-popup](https://cloud.githubusercontent.com/assets/4235126/4827003/87fc8d7e-5f75-11e4-9859-f8c9cc3d2547.png)

**Comment by sachalifs** [comment]
that "(SABER MÁS)", what does it mean?

**Comment by pazarando** [comment]
It display a small explanation of Demos.

Like this:
![demos04](https://cloud.githubusercontent.com/assets/4235126/4834868/bbd0de16-5fb1-11e4-97e2-afc327717d89.jpg)

**Comment by gvilarino** [comment]
I'd change 'saber más' to 'más info' and as the last sentence in the header, not between title and explanation.

**Comment by gvilarino** [comment]
Maybe remove it altogether, since there're explanation on the header. I believe we should keep in mind that every pixel we sacrifice for this is one more to hide the voting area from users.
