### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#35]
There's a new logo for DEMOS. We should use it.

**Comment by gvilarino** [comment]
Who has this? @pazarando ?

**Comment by sachalifs** [comment]
sorry @pazarando do you have the white colored logo?
![screen shot 2014-10-29 at 12 28 11 pm](https://cloud.githubusercontent.com/assets/1213542/4828450/3a06c44e-5f80-11e4-8082-d996cbd0cb90.png)

thanks

**Comment by pazarando** [comment]
I´ll send you by email the .svg

![demos_logo](https://cloud.githubusercontent.com/assets/4235126/4828578/36a588fc-5f81-11e4-9fe6-22be604c337f.png)
![demos-logo-header](https://cloud.githubusercontent.com/assets/4235126/4828579/36a94230-5f81-11e4-9135-87c4b44ab2c4.png)
![demos-logo-popup](https://cloud.githubusercontent.com/assets/4235126/4828580/36aa1a02-5f81-11e4-969d-2db940f88d6f.png)

**Comment by pazarando** [comment]
Believe it or not the white .png is in between the other two above :)

**Comment by gvilarino** [comment]
Good call, @pazarando , I'd have never realized
