### ISSUE TITLE
How it works link

### ISSUE THREAD

**Issue by vmariano** [DemocraciaEnRed/demos#4]
Could be a popover in the main page only the first time/login.

**Comment by gvilarino** [comment]
Yeah, add a menu item on the header and make the popover appear from it.

It should have an "Ok, got it" button on the bottom-left part.

Show if user hasn't seen it before, and until user clicks the button. Store that in a cookie for the time being.

**Comment by vmariano** [comment]
Done cookie/popover.
- TBD link path.
- where should point the popover.
- some issues with mobile and screen positioning, but first should resolve :arrow_up: 

Maybe @gvilarino or @slifszyc  has this data.

**Comment by gvilarino** [comment]
@vmariano:
- Path should be `/help/faq` (I think)
- The popove should be hooked to a 'How does this work?' element in the `header`
- As per :arrow_up:

**Comment by vmariano** [comment]
TBD mobile version.
