### ISSUE TITLE
Add button for tweeting to bill author

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#46]
It should have a predifined text, containing:
- author mention
- #YoVoto hashtag
- Bill's title
- Link to bill

All of this into one single message like

```
#YoVoto Una ley para los museos porteños de @SandraSenadora
```

The final text is to be defined by @mairwilliams

@pazarando where should we be putting this button? I believe there are two possible spots:
1. To the right of author's widget
2. In the space between content area and voting area (but still within the conten area box).

**Comment by pazarando** [comment]
Sorry the delay.

I prefer to add this button at the top part of the bill, because after user reads it I want them to vote better than to tweet. 

So I designed 3 different options, in the first two the tweet button is more related to the author, and goes better with the purpose of this issue.

In the third one the users will associate the "Tweet" with the whole bill, and if we are looking for that maybe we should go back to [https://github.com/DemocraciaEnRed/demos/issues/28](issue #28).

![demos04-01](https://cloud.githubusercontent.com/assets/4235126/4870668/05cbd358-617a-11e4-98a0-d4820ff916af.jpg)
![demos04-02](https://cloud.githubusercontent.com/assets/4235126/4870669/05cf89ee-617a-11e4-9182-78bd88401337.jpg)
![demos04-03](https://cloud.githubusercontent.com/assets/4235126/4870670/05d3ba14-617a-11e4-9942-78a8d9975694.jpg)

**Comment by gvilarino** [comment]
@piamancini @mairwilliams @afrizzera which one?

**Comment by piamancini** [comment]
Number 1 looks better.

**Comment by mairwilliams** [comment]
Yes, definitely, the first one. Is it necessary to have the "twittear" part? Did someone specifically ask for it? It's redundant. 

—

**Comment by gvilarino** [comment]
@mairwilliams think that user's don't assume functionality by looking at the twitter birdie. I believe the it should be 'talk to the author' or something.

**Comment by afrizzera** [comment]
I agree with @gvilarino. It should be "talk to the author" ("comunicate con el autor") and I would place it inside the box, near by "leer proyecto original". I don´t care about the bird. Let´s be literal     

I know it will sound "redundant" to you all. It is...but as it is one of the most important button, let´s be literal.

**Comment by gvilarino** [comment]
@pazarando can we get a sample of what @afrizzera is proposing?

**Comment by mairwilliams** [comment]
Talk to the author is fine. I just didn't like "twittear". I don't care about the bird either. 

—

**Comment by gvilarino** [comment]
I still believe doing it on the same 'space' as the author is better, because it's the same context. So íd go with option 1 with a text like proposed by @afrizzera.

The twitter logo may be redundant since users will find out anyway when they click on it.

**Comment by sachalifs** [comment]
@mairwilliams @gvilarino @afrizzera you can all see it on http://test-demos.herokuapp.com/

please tell me if it's ok so we can merge and close this issue

**Comment by afrizzera** [comment]
mmmmm...I still believe it should be placed below and that it should have a special status. 

I insist: it is one of the most important buttons of the whole platform.

**Comment by gvilarino** [comment]
I don't agree on that @afrizzera; I believe the most important thing is for users to vote. Taking any attention from that matter by emphasizing this button is shooting ourselves in the foot.

**Comment by gvilarino** [comment]
Besides, it's gonna break the visual system.

**Comment by sachalifs** [comment]
I deployed another layout on http://test-demos.herokuapp.com/ you can check it out and give me your feedback.

I like it the way it is now.

![screen shot 2014-11-02 at 7 03 30 pm](https://cloud.githubusercontent.com/assets/1213542/4877069/1cb5879a-62dc-11e4-887a-d853ca0a921a.png)

**Comment by afrizzera** [comment]
@gvilarino "I believe the most important thing is for users to vote": yes, of course...

@slifszyc, maybe a little smaller...And, sorry, I still think it should be placed below the summary...right below "ver el texto original"...

**Comment by sachalifs** [comment]
@pazarando will give us a hand with this

**Comment by pazarando** [comment]
I strongly belive that if its something related to the author needs to be near to the author infomation.
If not gets a little confusing the diferences between autor and bill.

Here two options of the "comunicate con el autor" button 

![demos04-06](https://cloud.githubusercontent.com/assets/4235126/4877184/6085a7ee-62e0-11e4-98bd-2bba63865cfb.jpg)
![demos04-07](https://cloud.githubusercontent.com/assets/4235126/4877185/608cf3f0-62e0-11e4-857b-30617ad79ad8.jpg)

**Comment by gvilarino** [comment]
:+1: to @pazarando 
I say we go with option 1 of the last proposal

**Comment by afrizzera** [comment]
The idea is to get in touch with the author to discuss the bill, this bill. To ask for more information or to give some kind of feedback. 
That´s why I think nbr 2 is the best option. I also think is much more elegant, I think the green one is too flashy.

**Comment by sachalifs** [comment]
Check it out again in http://test-demos.herokuapp.com/

**Comment by piamancini** [comment]
I like Option 1. @afrizzera the problem of it being below the 'orginal
text' is that the texts vary in size and it will therefore never be in the
same place.

P.
piamancini.com
t: @piamancini
s: piamancini
democracyos.org
democraciaenred.org

**Comment by gvilarino** [comment]
Tweet text should be:

```
#YoVoto Hola @>autorHandle<! Quiero decirte algo sobre tu proyecto >linkToBill<
```

**Comment by mairwilliams** [comment]
Hola Efren

de dónde sos?
DemocracyOS es open source, esa debería ser una de las principales
diferencias con Countable, que es software privativo.
Countable es muy atractivo visualmente. Hace algo en lo que nosotros
estamos todavía trabajando: seguir el estado de los proyectos de ley en su
camino dentro del congreso.
Miré mucho la herramienta, es realmente atractiva, probablemente la mejor
experiencia de usuario que haya visto en el ámbito de e-governance.
Pero no tiene espacio para el debate. Y no me parece que eso sea un simple
error. Cuando se diseña una herramienta para la política entra en juego lo
que sus diseñadores piensan de la democracia. Es evidente que el objetivo
detrás de Countable no es la deliberación.
Para nosotros, la democracia tiene inherentemente un componente de debate;
la argumentación es tan importante y poderosa como el voto. En este caso,
la diferencia es esencial.
Sólo pensamos la herramienta para procesos legislativos, por el momento.
Creemos que los ciudadanos pueden sumar valor, pero no pensamos en abolir
la representación. Los partidos políticos son instituciones valiosas cuya
importancia sostenemos, y si DemocracyOS les sirve para construir
propuestas u opiniones con sus simpatizantes, estaremos muy conformes. Pero
por otro lado, para asegurarnos de que el resultado de las votaciones
llegará al recinto, intentamos ganar una banca con el Partido de la Red. En
caso de ganar esa banca, tendríamos algo que ninguna otra herramienta
tiene: la seguridad de hacer efectivas las elecciones de los ciudadanos.
Los juegos de poder van mucho más allá de las soluciones tecnológicas. Lo
entendimos, y no estamos ofreciendo simplemente una solución en internet.

Gracias por hacer esas preguntas. Si tenes otras, no dudes en preguntar.

un beso!

M.

> _From: *Flavors.me noreply@flavors.me
> *Subject: *_Message from "Efren Ortiz" via your Flavors.me
> http://Flavors.me contact form*
> *Date: *10 November 2014 1:10:34 pm PST
> *To: *piamancini@gmail.com
> *Reply-To: *petortiz@gmail.com
> 
> Efren Ortiz - petortiz@gmail.com - sent you the following message from
> Flavors.me:
> 
> Hola Pia, me gusta mucho tu proyecto Democracy OS y me gustaria aprender
> mas.
> Como es Democracy OS distinta de un app como "Countable-Congress in your
> hands" por ejemplo?
> El objetivo de Democracy OS es lograr que las votaciones en
> parlamentos/congresos sean eventualmente echas directamente por los
> ciudadanos?
> Estan tratando de usar Democracy OS para que la gente tambien vote en
> elecciones? o solo para votos en parlamentos/congresos para aprobar leyes,
> etc? Gracias.
