### ISSUE TITLE
Make the text of progress bar bold

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#47]
![screen shot 2014-10-30 at 6 01 02 pm](https://cloud.githubusercontent.com/assets/2538465/4852074/ea92dd32-6077-11e4-995e-089ceda75313.png)

**Comment by jfresco** [comment]
It's already done in the `development` branch. See [this commit](https://github.com/DemocraciaEnRed/demos/commit/148e37a7e945acefe0975b125e32cf7095a89cdf#diff-6098fb3d04c8b71db25cabf88127f94d).

**Comment by gvilarino** [comment]
Closed by 148e37a7e945acefe0975b125e32cf7095a89cdf
