### ISSUE TITLE
Admin should be able to delete comments

### ISSUE THREAD

**Issue by sachalifs** [DemocraciaEnRed/demos#6]
At first we should make it so it works just like deleting your own comments, although an admin should have this option enabled for all comments.

Make sure there's a special legend for admins on the deletion confirmation, sort of: "You're an administrator. Consider the consequences of deleting this post."

**Comment by gvilarino** [comment]
After this basic implementation is done, I believe we should consider upgrading it to something that takes into special treatment those argument with existing replies. Sort of what happens with these comments in lanacion.com 's comments.

Also, we should consider providing a place for admins to enter a reason for deletions, so the comment's owner can get a specific reason for this.
