### ISSUE TITLE
Text sizes and styles

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#61]
Design says this:
![design](https://cloud.githubusercontent.com/assets/4235126/4870670/05d3ba14-617a-11e4-9942-78a8d9975694.jpg)

And what we got now is this:
![screen shot 2014-11-02 at 5 36 45 pm](https://cloud.githubusercontent.com/assets/2538465/4876752/7a71ac08-62d0-11e4-8bdd-df75be64c878.png)

@pazarando can you tell us what those fonts & sizes available? Maybe @mjlescano can fix them?

**Comment by gvilarino** [comment]
This is not done; I am seeing this:
![screen shot 2014-11-03 at 3 51 33 pm](https://cloud.githubusercontent.com/assets/2538465/4888168/16c11c00-638b-11e4-92df-a5f470ffc8ca.png)

**Comment by jfresco** [comment]
Here we are:
![image](https://cloud.githubusercontent.com/assets/4335188/4889412/8d8b8bcc-6395-11e4-8df1-f3800f78ed80.png)
