### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by gvilarino** [DemocraciaEnRed/demos#88]
Home screen is defined by #86 but will be preceded by a one-time tutorial that will explain briefly how the tool works.

The tutorial should be accessible again from a link in the header.

**Comment by gvilarino** [comment]
We're working with @afrizzera and @pazarando on the content for this one

**Comment by jfresco** [comment]
- [x] Generate `/tutorial`scaffolding
- [x] Add `sawTutorial` flag in database
- [x] Generate `/citizen/tutorial` endpoint to put `sawTutorial` in `true`
- [x] In `/`, redirect to `/tutorial` if `citizen.sawTutorial === false`
- [x] In `/tutorial`, invoke `/citizen/tutorial` if `citizen.sawTutorial === false`
- [x] In `/tutorial`, make template and styles
- [x] Include slider control
- [x] Integrate images to slider
